-- =====================================================
-- La_Fleuren — Supabase schema (run once in SQL Editor)
-- Free tier is plenty for a boutique store like this.
-- =====================================================

-- 1. PRODUCTS -----------------------------------------
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  price numeric(10,2) not null,
  icon text,              -- emoji fallback shown when there's no photo, e.g. '📿'
  image_url text,         -- optional real product photo URL
  badge text,              -- small label e.g. 'Best seller', 'New', 'Gift'
  in_stock boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

alter table products enable row level security;

-- Anyone can view products (needed for the storefront to load them)
create policy "Public can view products"
on products for select
to anon
using (true);

-- Seed with the original 4 sample products so the site works immediately
insert into products (name, category, price, icon, badge, sort_order) values
  ('Floral Pearl Necklace', 'Necklaces', 29, '📿', 'Best seller', 1),
  ('Rose Charm Bracelet', 'Bracelets', 19, '💫', 'New', 2),
  ('Elegant Moon Earrings', 'Earrings', 15, '🌙', 'Gift', 3),
  ('Princess Hair Clip Set', 'Hair Accessories', 12, '🎀', 'Cute', 4);


-- 2. ORDERS --------------------------------------------
create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_number text unique not null,
  customer_name text not null,
  phone text not null,
  email text,
  address text not null,
  notes text,
  items jsonb not null,          -- [{ id, name, price, qty }, ...]
  subtotal numeric(10,2) not null,
  status text not null default 'new',   -- new / processing / shipped / delivered / cancelled
  created_at timestamptz not null default now()
);

alter table orders enable row level security;

-- Anyone can place an order (public storefront, no login required)
create policy "Public can insert orders"
on orders for insert
to anon
with check (true);

-- Note: SELECT is intentionally NOT open to anon, so customers can't browse
-- each other's orders. View/manage orders from the Supabase Table Editor,
-- or add an authenticated policy later if you build an admin dashboard.


-- 3. NEWSLETTER SUBSCRIBERS ------------------------------
create table if not exists newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  created_at timestamptz not null default now()
);

alter table newsletter_subscribers enable row level security;

create policy "Public can subscribe"
on newsletter_subscribers for insert
to anon
with check (true);
